//IF ANG REQUEST IS TRUE - SUCESS
export const MAKE_REQUEST='MAKE_REQUEST'

//IF ANG REQUEST IS FALSE - ERROR
export const FAILED_REQUEST='FAILED_REQUEST'

//MAGFETCH UG MGA STUDENTS
export const GET_USER_LIST='GET_USER_LIST'

//IF MAGDELETE UG USER
export const DELETE_USER='DELETE_USER'

//ADD USER
export const ADD_USER='ADD_USER'

//UPDATE USER
export const UPDATE_USER='UPDATE_USER'

//KUHAON ANG USER INFO OBJECT PARA E UPDATE
export const GET_USER_OBJECT_DATA='GET_USER_OBJECT_DATA'