//IF ANG REQUEST IS TRUE - SUCESS
export const MAKE_REQUEST='MAKE_REQUEST'
//IF ANG REQUEST IS FALSE - ERROR
export const FAILED_REQUEST='FAILED_REQUEST'
//IF SUCCESS 
export const GET_USER_LIST='GET_USER_LIST'